USE [master]
GO
/****** Object:  Database [SisMelodias]    Script Date: 22/9/2025 21:20:35 ******/
CREATE DATABASE [SisMelodias]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SisMelodias', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\SisMelodias.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SisMelodias_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\SisMelodias_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SisMelodias] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SisMelodias].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SisMelodias] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SisMelodias] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SisMelodias] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SisMelodias] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SisMelodias] SET ARITHABORT OFF 
GO
ALTER DATABASE [SisMelodias] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [SisMelodias] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SisMelodias] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SisMelodias] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SisMelodias] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SisMelodias] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SisMelodias] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SisMelodias] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SisMelodias] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SisMelodias] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SisMelodias] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SisMelodias] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SisMelodias] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SisMelodias] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SisMelodias] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SisMelodias] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SisMelodias] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SisMelodias] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SisMelodias] SET  MULTI_USER 
GO
ALTER DATABASE [SisMelodias] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SisMelodias] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SisMelodias] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SisMelodias] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SisMelodias] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SisMelodias] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SisMelodias] SET QUERY_STORE = ON
GO
ALTER DATABASE [SisMelodias] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [SisMelodias]
GO
/****** Object:  Table [dbo].[categoria]    Script Date: 22/9/2025 21:20:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[categoria](
	[Id_categoria] [int] IDENTITY(1,1) NOT NULL,
	[descripcion_cat] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_categoria] PRIMARY KEY CLUSTERED 
(
	[Id_categoria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[cliente]    Script Date: 22/9/2025 21:20:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[cliente](
	[Id_cliente] [int] IDENTITY(1,1) NOT NULL,
	[nombre_cliente] [nvarchar](50) NOT NULL,
	[apellido_cliente] [nvarchar](50) NOT NULL,
	[dni_cliente] [int] NOT NULL,
	[correo_cliente] [nvarchar](50) NOT NULL,
	[telefono_cliente] [nvarchar](10) NOT NULL,
	[direccion_cliente] [nvarchar](50) NOT NULL,
	[fecha_cliente] [datetime] NOT NULL,
 CONSTRAINT [PK_cliente] PRIMARY KEY CLUSTERED 
(
	[Id_cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[telefono_cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[correo_cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[dni_cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[detalle_venta]    Script Date: 22/9/2025 21:20:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[detalle_venta](
	[Id_detalle_venta] [int] IDENTITY(1,1) NOT NULL,
	[Id_producto] [int] NOT NULL,
	[precio_unitario] [decimal](18, 2) NOT NULL,
	[cantidad] [int] NOT NULL,
	[Id_venta] [int] NOT NULL,
 CONSTRAINT [PK_detalle_venta] PRIMARY KEY CLUSTERED 
(
	[Id_detalle_venta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[empleado]    Script Date: 22/9/2025 21:20:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[empleado](
	[Id_empleado] [int] IDENTITY(1,1) NOT NULL,
	[nombre_empleado] [nvarchar](50) NOT NULL,
	[apellido_empleado] [nvarchar](50) NOT NULL,
	[dni_empleado] [int] NOT NULL,
	[correo_empleado] [nvarchar](50) NOT NULL,
	[telefono_empleado] [nvarchar](10) NOT NULL,
	[direccion_empleado] [nvarchar](50) NOT NULL,
	[usuario] [nvarchar](50) NOT NULL,
	[Id_perfil] [int] NOT NULL,
	[fecha_empleado] [datetime] NOT NULL,
	[estado_empleado] [nvarchar](50) NOT NULL,
	[contraseña] [nvarchar](100) NULL,
 CONSTRAINT [PK_empleado] PRIMARY KEY CLUSTERED 
(
	[Id_empleado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[dni_empleado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[correo_empleado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[telefono_empleado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[pago]    Script Date: 22/9/2025 21:20:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[pago](
	[Id_pago] [int] IDENTITY(1,1) NOT NULL,
	[descripcion_pago] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_pago] PRIMARY KEY CLUSTERED 
(
	[Id_pago] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[perfil]    Script Date: 22/9/2025 21:20:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[perfil](
	[Id_perfil] [int] IDENTITY(1,1) NOT NULL,
	[descripcion_perfil] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_perfil] PRIMARY KEY CLUSTERED 
(
	[Id_perfil] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[producto]    Script Date: 22/9/2025 21:20:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[producto](
	[Id_producto] [int] IDENTITY(1,1) NOT NULL,
	[nombre_producto] [nvarchar](50) NOT NULL,
	[estado_producto] [nvarchar](50) NOT NULL,
	[precio] [decimal](18, 2) NOT NULL,
	[stock] [int] NOT NULL,
	[Id_categoria] [int] NOT NULL,
	[descripcion_producto] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_producto] PRIMARY KEY CLUSTERED 
(
	[Id_producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[venta]    Script Date: 22/9/2025 21:20:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[venta](
	[Id_venta] [int] IDENTITY(1,1) NOT NULL,
	[Id_empleado] [int] NOT NULL,
	[Id_pago] [int] NOT NULL,
	[Id_cliente] [int] NOT NULL,
	[fecha] [datetime] NOT NULL,
	[total] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_venta] PRIMARY KEY CLUSTERED 
(
	[Id_venta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Fk_detalle_venta_producto]    Script Date: 22/9/2025 21:20:36 ******/
CREATE NONCLUSTERED INDEX [IX_Fk_detalle_venta_producto] ON [dbo].[detalle_venta]
(
	[Id_producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Fk_venta_detalle_venta]    Script Date: 22/9/2025 21:20:36 ******/
CREATE NONCLUSTERED INDEX [IX_Fk_venta_detalle_venta] ON [dbo].[detalle_venta]
(
	[Id_venta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Fk_empleado_perfil]    Script Date: 22/9/2025 21:20:36 ******/
CREATE NONCLUSTERED INDEX [IX_Fk_empleado_perfil] ON [dbo].[empleado]
(
	[Id_perfil] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Fk_producto_categoria]    Script Date: 22/9/2025 21:20:36 ******/
CREATE NONCLUSTERED INDEX [IX_Fk_producto_categoria] ON [dbo].[producto]
(
	[Id_categoria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Fk_venta_cliente]    Script Date: 22/9/2025 21:20:36 ******/
CREATE NONCLUSTERED INDEX [IX_Fk_venta_cliente] ON [dbo].[venta]
(
	[Id_cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Fk_venta_empleado]    Script Date: 22/9/2025 21:20:36 ******/
CREATE NONCLUSTERED INDEX [IX_Fk_venta_empleado] ON [dbo].[venta]
(
	[Id_empleado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Fk_venta_pago]    Script Date: 22/9/2025 21:20:36 ******/
CREATE NONCLUSTERED INDEX [IX_Fk_venta_pago] ON [dbo].[venta]
(
	[Id_pago] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[detalle_venta]  WITH CHECK ADD  CONSTRAINT [Fk_detalle_venta_producto] FOREIGN KEY([Id_producto])
REFERENCES [dbo].[producto] ([Id_producto])
GO
ALTER TABLE [dbo].[detalle_venta] CHECK CONSTRAINT [Fk_detalle_venta_producto]
GO
ALTER TABLE [dbo].[detalle_venta]  WITH CHECK ADD  CONSTRAINT [Fk_venta_detalle_venta] FOREIGN KEY([Id_venta])
REFERENCES [dbo].[venta] ([Id_venta])
GO
ALTER TABLE [dbo].[detalle_venta] CHECK CONSTRAINT [Fk_venta_detalle_venta]
GO
ALTER TABLE [dbo].[empleado]  WITH CHECK ADD  CONSTRAINT [Fk_empleado_perfil] FOREIGN KEY([Id_perfil])
REFERENCES [dbo].[perfil] ([Id_perfil])
GO
ALTER TABLE [dbo].[empleado] CHECK CONSTRAINT [Fk_empleado_perfil]
GO
ALTER TABLE [dbo].[producto]  WITH CHECK ADD  CONSTRAINT [Fk_producto_categoria] FOREIGN KEY([Id_categoria])
REFERENCES [dbo].[categoria] ([Id_categoria])
GO
ALTER TABLE [dbo].[producto] CHECK CONSTRAINT [Fk_producto_categoria]
GO
ALTER TABLE [dbo].[venta]  WITH CHECK ADD  CONSTRAINT [Fk_venta_cliente] FOREIGN KEY([Id_cliente])
REFERENCES [dbo].[cliente] ([Id_cliente])
GO
ALTER TABLE [dbo].[venta] CHECK CONSTRAINT [Fk_venta_cliente]
GO
ALTER TABLE [dbo].[venta]  WITH CHECK ADD  CONSTRAINT [Fk_venta_empleado] FOREIGN KEY([Id_empleado])
REFERENCES [dbo].[empleado] ([Id_empleado])
GO
ALTER TABLE [dbo].[venta] CHECK CONSTRAINT [Fk_venta_empleado]
GO
ALTER TABLE [dbo].[venta]  WITH CHECK ADD  CONSTRAINT [Fk_venta_pago] FOREIGN KEY([Id_pago])
REFERENCES [dbo].[pago] ([Id_pago])
GO
ALTER TABLE [dbo].[venta] CHECK CONSTRAINT [Fk_venta_pago]
GO
USE [master]
GO
ALTER DATABASE [SisMelodias] SET  READ_WRITE 
GO
